In [ ]:
    1. Write a Python Program to Add Two Matrices?

In [11]:
import numpy as np 
a = np.linspace(2,30,15).reshape(3,5)
b = np.linspace(30,60,15).reshape(3,5)
c = a + b
print("sum of a +b ",c)

sum of a +b  [[32.         36.14285714 40.28571429 44.42857143 48.57142857]
 [52.71428571 56.85714286 61.         65.14285714 69.28571429]
 [73.42857143 77.57142857 81.71428571 85.85714286 90.        ]]


In [ ]:
    2. Write a Python Program to Multiply Two Matrices?

In [14]:
import numpy as np 
a = np.linspace(2,30,15).reshape(3,5)
b = np.linspace(30,60,15).reshape(5,3)
c = a @ b
print("multiplication of a  x b \n",c)

multiplication of a  x b 
 [[1414.28571429 1478.57142857 1542.85714286]
 [3557.14285714 3728.57142857 3900.        ]
 [5700.         5978.57142857 6257.14285714]]


In [ ]:
    3. Write a Python Program to Transpose a Matrix?

In [15]:
import numpy as np 
a = np.linspace(2,30,15).reshape(3,5)

In [18]:
a

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.]])

In [17]:
a.T

array([[ 2., 12., 22.],
       [ 4., 14., 24.],
       [ 6., 16., 26.],
       [ 8., 18., 28.],
       [10., 20., 30.]])

In [ ]:
    4. Write a Python Program to Sort Words in Alphabetic Order?

In [32]:
string_2=" i love my country and i am proud of it. sarea jahasi acha"
list_words =string_2.split()
list_words.sort()
for i in list_words:
    print(i)


acha
am
and
country
i
i
it.
jahasi
love
my
of
proud
sarea


In [ ]:
    5. Write a Python Program to Remove Punctuation From a String?

In [ ]:
puncuation = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
string_1 ="my !! name is : Shijin Ms @ I am 32 #"
no_punc=''
for char in string_1:
    if char not in puncuation:
        no_punc +=char
print(no_punc)